### ISSUE TITLE
Custom tracking vs. auto-tagging

### ISSUE THREAD

**Issue by ladislav89v** [jzdarsa/google_ads_script_utm_tracking#2]
Hi there. First of all, thanks for this; it's quite a lifesaver when it comes to untracked campaigns. However, I wonder how this works alongside autotagging. Does it function as a backup when autotagging isn't tracked, or does it override it?
Thank you for the explanation.

**Comment by jzdarsa** [comment]
Hi there, gclid is appended to the url so the LP url still carries the gclid. And in GA4, if Google is able to match it against their Google Ads gclid table, GA4 will overwrite the utm parameters. But if the campaign would end up with (organic) in the name (they could not match it because of consent), Google will keep the UTM parameters.
